routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@welcome')->name('welcome');
Route::get('artigiano/{command}/{param}', ['as' => 'cache', 'uses' => 'CacheController@show']); 
/*
Route::get('/', function () {
    return View::make('front-page');
});
*/

//Auth::routes();
/** AUTH ROUTES  
 */

 // Authentication Routes...
Route::get('login',  [ 'as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm' ]);
Route::post('login', [ 'as' => '', 'uses' => 'Auth\LoginController@login' ]);
Route::any('logout', [ 'as' => 'logout', 'uses' => 'Auth\LoginController@logout' ]);
  
  // Password Reset Routes...
Route::post('password/email', [ 'as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail' ]);
Route::get('password/reset', [ 'as' => 'password.request', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm' ]);
Route::post('password/reset', [ 'as' => 'password.update', 'uses' => 'Auth\ResetPasswordController@reset' ]);
Route::get('password/reset/{token}', [ 'as' => 'password.reset', 'uses' => 'Auth\ResetPasswordController@showResetForm' ]);
  
// Registration Routes...
Route::get('register', [ 'as' => 'register', 'uses' => 'Auth\RegisterController@showRegistrationForm' ]);
Route::post('register', [ 'as' => '', 'uses' => 'Auth\RegisterController@register' ]);
Route::get('register-club', [ 'as' => 'register-club', 'uses' => 'Auth\RegisterController@showRegistrationClubForm' ]);
Route::post('register-club', [ 'as' => 'register-club', 'uses' => 'Auth\RegisterController@registerClub' ]);
  /** END AUTH ROUTES */

Route::group(['middleware' => ['auth']], function () {    

  Route::get('edit-profile', ['as' => 'edit-profile', 'uses' => 'UserController@editProfile']);
  Route::post('/update_profile', ['as'=>'update_profile', 'uses'=>'UserController@updateProfile']);
  Route::post('/gallery/image/{id_image}/delete', ['as'=>'gallery.image.delete', 'uses'=>'UserController@deleteImage']);

  Route::post('/tournamentSubscription', ['as' => 'tournamentSubscription', 'uses' => 'PlayerController@tournamentSubscription']);

});

Route::group(['middleware' => ['auth']], function () {    
        

    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function() {                    

        Route::get('/profile', ['as' => 'profile', 'uses' => 'UserController@profile']);                
        Route::post('/update_profile', ['as'=>'update_profile', 'uses'=>'UserController@updateProfile']);
        
        
        Route::get('/home', ['as'=>'home', 'uses' => 'HomeController@index'] );        
        Route::post('/upload_profile_image', ['as'=>'upload_profile_image', 'uses'=>'UserController@upload_profile_image']);
        Route::post('/remove_profile_image', ['as'=>'remove_profile_image', 'uses'=>'UserController@remove_profile_image']);
        
        Route::get('/rounds/{id_group}/index', ['as' => 'rounds.index', 'uses' => 'RoundController@index']);        
        Route::get('groups/{id_group}/classification', ['as' => 'group.classification', 'uses' => 'GroupController@classification']);            
        
        Route::post('groups/{id_group}/calendar/make', ['as' => 'make_group_calendar', 'uses' => 'GroupController@makeGroupCalendar']);  
        
        Route::get('bracket/{id_bracket}/show', ['as' => 'show_bracket', 'uses' => 'BracketController@show']);        
        Route::get('bracket/{id_bracket}/show_macro', ['as' => 'show_macro_bracket', 'uses' => 'BracketController@showMacro']);        

        Route::get('rankings/{gender}/year/{year}', ['as' => 'rankings_year', 'uses' => 'RankingController@index']);
        Route::get('rankings/{gender}/live', ['as' => 'rankings_live', 'uses' => 'RankingController@live']);
        
        Route::get('player/search', ['as' => 'search', 'uses' => 'UserController@searchPlayer']);
        Route::get('player/{id_player}/get', ['as' => 'search', 'uses' => 'UserController@get']);

        Route::get('club/search', ['as' => 'search_club', 'uses' => 'ClubController@search']);  
        Route::get('club/{id_club}/get', ['as' => 'search', 'uses' => 'ClubController@get']);                
        
        Route::post('/matches/schedule', ['as' => 'matches.schedule', 'uses' => 'MatchController@schedule']);   
        Route::post('/matches/del_schedule', ['as' => 'matches.del_schedule', 'uses' => 'MatchController@delSchedule']);   
        
        Route::post('/macro_matches/schedule', ['as' => 'macro_matches.schedule', 'uses' => 'MacroMatchController@schedule']);   
        Route::post('/macro_matches/del_schedule', ['as' => 'macro_matches.del_schedule', 'uses' => 'MacroMatchController@delSchedule']);   
        Route::get('/macro_teams/{id_macro_team}/show', ['as' => 'show_macro_team', 'uses' => 'MacroTeamController@edit']);   
        Route::post('/macro_teams/update', ['as' => 'macro_team.update', 'uses' => 'MacroTeamController@update']);   
        
        Route::post('/scores/store', ['as' => 'scores.store', 'uses' => 'ScoreController@store']);                             

        Route::get('images', ['as' => 'images.index', 'uses' => 'ImageController@index']);                                        
        Route::get('images/create', ['as' => 'images.create', 'uses' => 'ImageController@create']);                                
        Route::post('images/store', ['as' => 'images.store', 'uses' => 'ImageController@store']);                         
        Route::post('images/destroy', ['as' => 'images.destroy', 'uses' => 'ImageController@destroy']);                         
        
        Route::get('images/match/{id_match}', ['as' => 'images.match.index', 'uses' => 'ImageController@imgMatchList']);
        Route::get('images/match/{id_match}/create', ['as' => 'images.match.create', 'uses' => 'ImageController@imgMatchCreate']);
        Route::get('images/match/{id_match}/delete', ['as' => 'images.match.delete', 'uses' => 'ImageController@imgMatchDelete']);                               
    
        
        Route::group(['middleware' => ['admin']], function () {
            Route::resource('users', 'UserController');            
            
            Route::resource('countries', 'CountryController');
            Route::resource('cities', 'CityController');
            Route::resource('zones', 'ZoneController');

            Route::resource('tournamentTypes', 'TournamentTypeController');
            Route::resource('categoryTypes', 'CategoryTypeController');
            
            Route::resource('editions', 'EditionController');    
            /*
            Route::get('editions', ['as' => 'editions.index', 'uses' => 'EditionController@index']);
            Route::get('editions/create', ['as' => 'editions.create', 'uses' => 'EditionController@create']);
            Route::post('editions/store', ['as' => 'editions.store', 'uses' => 'EditionController@store']);
            Route::get('editions/{id_edition}', ['as' => 'editions.show', 'uses' => 'EditionController@show']);
            Route::get('editions/{id_edition}/edit', ['as' => 'editions.edit', 'uses' => 'EditionController@edit']);
            Route::post('editions/update', ['as' => 'editions.update', 'uses' => 'EditionController@update']);
            Route::delete('editions/{id_edition}', ['as' => 'editions.delete', 'uses' => 'EditionController@destroy']);
            */
            
            Route::delete('subscription/{id_subscription}/remove', 'SubscriptionController@destroy');
            Route::delete('macro_subscription/{id_subscription}/remove', 'MacroSubscriptionController@destroy');
            
            /** Tournament */
            Route::post('tournaments/store', 'TournamentController@store');
            Route::get('tournaments/{id_tournament}/edit', 'TournamentController@edit');
            Route::post('tournaments/{id_tournament}/update', 'TournamentController@update');
            Route::delete('tournaments/{id_tournament}/delete', 'TournamentController@destroy');
            Route::post('tournaments/generate', 'TournamentController@generate');
            Route::post('tournaments/subscribe', ['as' => 'subscribe_team', 'uses' => 'TournamentController@subscribe']);
            Route::get('tournaments/{id_tournament}/subscriptions', ['as' => 'subscriptions', 'uses' => 'TournamentController@subscriptions']);
            Route::get('tournaments/{id_tournament}/brackets', ['as' => 'brackets', 'uses' => 'TournamentController@brackets']);
            
            Route::get('bracket/{id_bracket}/prepare', ['as' => 'bracket_prepare', 'uses' => 'BracketController@prepare']);            
            Route::post('bracket/generate', ['as' => 'bracket_prepare', 'uses' => 'BracketController@generate']);            
            Route::post('bracket/{id_bracket}/delete', ['as' => 'bracket_delete', 'uses' => 'BracketController@destroy']);            
            Route::post('bracket/create', ['as' => 'bracket_create', 'uses' => 'BracketController@create']);                        
            
            Route::get('phase/{id_phase}/generate', ['as' => 'phase_matches', 'uses' => 'PhaseController@generate']);            

            Route::post('tournaments/assigncategories', ['as' => 'assigncategories', 'uses' => 'TournamentController@assigncategories']);
                        
            Route::get('/division/{id_division}/index', ['as' => 'divisions.index', 'uses' => 'DivisionController@index']);            
            Route::get('/division/{id_division}/edit', ['as' => 'divisions.edit', 'uses' => 'DivisionController@edit']);            

app/Models/Image.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Image
 * @package App\Models
 * @version April 15, 2019, 7:14 pm UTC
 *
 * @property \Illuminate\Database\Eloquent\Collection editions
 * @property \Illuminate\Database\Eloquent\Collection galleries
 * @property \Illuminate\Database\Eloquent\Collection new
 * @property string path
 * @property string label
 */
class Image extends Model
{
    //use SoftDeletes;

    public $table = 'images';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'path',
        'label',
        'id_user',
        'id_match'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'path' => 'string',
        'label' => 'string',
        'id_user' => 'id_user',
        'id_match' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'path' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function editions()
    {
        return $this->hasMany(\App\Models\Edition::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     **/
    public function galleries()
    {
        return $this->belongsToMany(\App\Models\Gallery::class, 'gallery_images');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function news()
    {
        return $this->hasMany(\App\Models\News::class);
    }
}

app/Http/Controllers/Admin/ImageController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Support\Facades\Auth;
use App\Http\Requests\CreateImageRequest;
use App\Http\Requests\UpdateImageRequest;
use App\Repositories\ImageRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

use App\Models\Image;

class ImageController extends AppBaseController
{
    /** @var  ImageRepository */
    private $imageRepository;

    public function __construct(ImageRepository $imageRepo)
    {
        $this->imageRepository = $imageRepo;
    }

    /**
     * Display a listing of the Image.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $images = $this->imageRepository->all();

        return view('admin.images.index')
            ->with('images', $images);
    }

    /**
     * Show the form for creating a new Image.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.images.create');
    }

    /**
     * Store a newly created Image in storage.
     *
     * @param CreateImageRequest $request
     *
     * @return Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        
        foreach( $request->allFiles() as $k => $img ){

            //echo $img->getClientOriginalName();                         
            $path = $img->store('images');          
            $image = new Image;
            $image->path = $path;
            $image->label = $img->getClientOriginalName(); 
            $image->id_user = $input['id_user'];
            $image->id_match = $input['id_match'];
            $image->save();

        }
        
        return response('ok', 200);

    }

    /**
     * Display the specified Image.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $image = $this->imageRepository->find($id);

        if (empty($image)) {
            Flash::error('Image not found');

            return redirect(route('admin.images.index'));
        }

        return view('admin.images.show')->with('image', $image);
    }

    /**
     * Show the form for editing the specified Image.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $image = $this->imageRepository->find($id);

        if (empty($image)) {
            Flash::error('Image not found');

            return redirect(route('admin.images.index'));
        }

        return view('admin.images.edit')->with('image', $image);
    }

    /**
     * Update the specified Image in storage.
     *
     * @param int $id
     * @param UpdateImageRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateImageRequest $request)
    {
        $image = $this->imageRepository->find($id);

        if (empty($image)) {
            Flash::error('Image not found');

            return redirect(route('admin.images.index'));
        }

        $image = $this->imageRepository->update($request->all(), $id);

        Flash::success('Image updated successfully.');

        return redirect(route('admin.images.index'));
    }

    /**
     * Remove the specified Image from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy(Request $request)
    {
        $input = $request->all();

        foreach($input['del_image'] as $id_image):
            Image::where('id', '=', $id_image)->delete();
        endforeach;

        return redirect(route('admin.images.match.index', ['id_match' => $input['id_match']]));
    }


    public function imgMatchList($id_match){
        
        $images = Image::where('id_match', '=', $id_match)->get();

        return view('admin.images.index')
             ->with('images', $images)
             ->with('id_match', $id_match)
             ->with('flag_delete', false)
             ;

    }

    public function imgMatchDelete($id_match){

        $images = Image::where('id_match', '=', $id_match)->get();

        return view('admin.images.index')
                ->with('images', $images)
                ->with('id_match', $id_match)
                ->with('flag_delete', true)
                ;
    }

    public function imgMatchCreate($id_match){
        return view('admin.images.create')
                ->with('id_match', $id_match)
                ->with('id_user', Auth::id())                
                ->with('flag_delete', false)
                ;
    }

    
}

resources/views/admin/images/create.blade.php
@extends('admin.layouts.app')

@section('css')
<link rel="stylesheet" href="{!! asset('public/css/dropzone.css') !!}" />
@endsection

@section('content')
    <section class="content-header">
        <h1>
            Carica immagini
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')

        <span>Clicca nello spazio qui sotto o trascina dentro le immmagini</span>
        <div id="my-dropzone" style="height: 300px; width: 100%; padding: 20px; border: 1px solid #ccc; background-color: #fff"></form>                              
        </div>

        @csrf
        <input type="hidden" name="id_user" value="{!! $id_user !!}">
        <input type="hidden" name="id_match" value="{!! $id_match !!}">
        <br>
        <a href="{!! route('admin.images.match.index', ['id_match' => $id_match]) !!}" class="btn btn-primary">Indietro</a>

    </div>

@endsection

@section('scripts')
<script src="{!! asset('public/js/dropzone.js') !!}"></script>
<script>
$(document).ready(function(){

    var token = $('input[name="_token"]').val();
    var id_match = $('input[name="id_match"]').val();
    var id_user = $('input[name="id_user"]').val();    

    var myDropzone = new Dropzone("#my-dropzone", {
        url: "{!! route('admin.images.store') !!}"
    });
    $("#my-dropzone").addClass("dropzone");
    myDropzone.on('sending', function(file, xhr, formData){
        console.log("dropzone sendind", formData);
        formData.append('_token', token);
        formData.append('id_user', id_user);
        formData.append('id_match', id_match);
    });
});
</script>
@endsection

resources/views/admin/images/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Image
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($image, ['route' => ['admin.images.update', $image->id], 'method' => 'patch']) !!}

                        

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/images/fields.blade.php
<!-- Path Field -->
<div class="form-group col-sm-6">
    {!! Form::label('path', 'Path:') !!}
    {!! Form::text('path', null, ['class' => 'form-control']) !!}
</div>

<!-- Label Field -->
<div class="form-group col-sm-6">
    {!! Form::label('label', 'Label:') !!}
    {!! Form::text('label', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('admin.images.index') !!}" class="btn btn-default">{!! trans('labels.cancel'); !!}</a>
</div>

resources/views/admin/images/index.blade.php
@extends('admin.layouts.app')



@section('content')
    <section class="content-header">
        <h1 class="pull-left">Multimedia</h1>        
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            @if( $flag_delete )
                <form action="{!! route('admin.images.destroy') !!}" method="post">
                @csrf()
                <input type="hidden" name="id_match" value="{!! $id_match !!}">
            @endif

            <div class="box-body">                

                @include('admin.images.table')                

            </div>
        </div>

        @if( $flag_delete )
                <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i> Elimina immagini selezionate</button>
                <a href="{{ config('app.url') }}/admin/images/match/{!! $id_match !!}" class="btn btn-default">Annulla</a>
            </form>
        @endif

        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/admin/images/show.blade.php
f@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Image
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('admin.images.show_fields')
                    <a href="{!! route('admin.images.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/images/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $image->id !!}</p>
</div>

<!-- Path Field -->
<div class="form-group">
    {!! Form::label('path', 'Path:') !!}
    <p>{!! $image->path !!}</p>
</div>

<!-- Label Field -->
<div class="form-group">
    {!! Form::label('label', 'Label:') !!}
    <p>{!! $image->label !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $image->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $image->updated_at !!}</p>
</div>

resources/views/admin/images/table.blade.php
@section('css')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
@endsection

<div class="row">
    <div class="col-xs-12">        
        @if( !$flag_delete )
        <a href="{{ config('app.url') }}/admin/images/match/{!! $id_match !!}/create" class="btn btn-primary"><i class="fa fa-upload"></i> Carica immagini</a>
        <a href="{{ config('app.url') }}/admin/images/match/{!! $id_match !!}/delete" class="btn btn-danger"><i class="fa fa-trash"></i> Elimina immagini</a>
        @endif        
    </div>
</div>
<br>

@foreach($images as $image)    
    <div style="width: 100px; display: inline-block; text-align: center; margin-bottom: 10px;">
        @if(!$flag_delete)
        <a data-fancybox="gallery" title="" style="width: 100px; height: 100px" href="{!! url('/storage/app/'.$image->path) !!}">
        @endif
            <div alt="" class="image-card" style="width: 100px; height: 100px; display: inline-block; background:url('{!! url('/storage/app/'.$image->path) !!}'); background-size: cover;"></div>    
            @if( $flag_delete )            
                <input type="checkbox" name="del_image[]" value="{!! $image->id !!}">
            @endif
        @if(!$flag_delete)
        </a>        
        @endif
    </div>
@endforeach

@section('scripts')
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
@endsection