routes/web.php
        Route::group(['middleware' => ['admin']], function () {
            Route::resource('users', 'UserController');            
            
            Route::resource('countries', 'CountryController');
            Route::resource('cities', 'CityController');
            Route::resource('zones', 'ZoneController');

            Route::resource('tournamentTypes', 'TournamentTypeController');
            Route::resource('categoryTypes', 'CategoryTypeController');
            
            Route::resource('editions', 'EditionController');    
            /*
            Route::get('editions', ['as' => 'editions.index', 'uses' => 'EditionController@index']);
            Route::get('editions/create', ['as' => 'editions.create', 'uses' => 'EditionController@create']);
            Route::post('editions/store', ['as' => 'editions.store', 'uses' => 'EditionController@store']);
            Route::get('editions/{id_edition}', ['as' => 'editions.show', 'uses' => 'EditionController@show']);
            Route::get('editions/{id_edition}/edit', ['as' => 'editions.edit', 'uses' => 'EditionController@edit']);
            Route::post('editions/update', ['as' => 'editions.update', 'uses' => 'EditionController@update']);
            Route::delete('editions/{id_edition}', ['as' => 'editions.delete', 'uses' => 'EditionController@destroy']);
            */
            
            Route::delete('subscription/{id_subscription}/remove', 'SubscriptionController@destroy');
            Route::delete('macro_subscription/{id_subscription}/remove', 'MacroSubscriptionController@destroy');
            
            /** Tournament */
            Route::post('tournaments/store', 'TournamentController@store');
            Route::get('tournaments/{id_tournament}/edit', 'TournamentController@edit');
            Route::post('tournaments/{id_tournament}/update', 'TournamentController@update');
            Route::delete('tournaments/{id_tournament}/delete', 'TournamentController@destroy');
            Route::post('tournaments/generate', 'TournamentController@generate');
            Route::post('tournaments/subscribe', ['as' => 'subscribe_team', 'uses' => 'TournamentController@subscribe']);
            Route::get('tournaments/{id_tournament}/subscriptions', ['as' => 'subscriptions', 'uses' => 'TournamentController@subscriptions']);
            Route::get('tournaments/{id_tournament}/brackets', ['as' => 'brackets', 'uses' => 'TournamentController@brackets']);
            
            Route::get('bracket/{id_bracket}/prepare', ['as' => 'bracket_prepare', 'uses' => 'BracketController@prepare']);            
            Route::post('bracket/generate', ['as' => 'bracket_prepare', 'uses' => 'BracketController@generate']);            
            Route::post('bracket/{id_bracket}/delete', ['as' => 'bracket_delete', 'uses' => 'BracketController@destroy']);            
            Route::post('bracket/create', ['as' => 'bracket_create', 'uses' => 'BracketController@create']);                        
            
            Route::get('phase/{id_phase}/generate', ['as' => 'phase_matches', 'uses' => 'PhaseController@generate']);            

            Route::post('tournaments/assigncategories', ['as' => 'assigncategories', 'uses' => 'TournamentController@assigncategories']);
                        
            Route::get('/division/{id_division}/index', ['as' => 'divisions.index', 'uses' => 'DivisionController@index']);            
            Route::get('/division/{id_division}/edit', ['as' => 'divisions.edit', 'uses' => 'DivisionController@edit']);            
            Route::delete('/division/{id_division}/remove', ['as' => 'divisions.remove', 'uses' => 'DivisionController@destroy']);            
            Route::post('/division/create', ['as' => 'divisions.create', 'uses' => 'DivisionController@create']);            

            Route::post('/groups/remove', ['as' => 'groups.remove', 'uses' => 'GroupController@remove']);
            Route::get('/groups/prepare', ['as' => 'groups.prepare', 'uses' => 'GroupController@prepare']);
            Route::post('/groups/generate', ['as' => 'groups.generate', 'uses' => 'GroupController@generate']);                        
            Route::post('/groups/online', ['as' => 'groups.online', 'uses' => 'GroupController@online']);            
            Route::get('/groups/{id_group}/editRounds', ['as' => 'groups.edit_rounds', 'uses' => 'GroupController@showEditRounds']);
            Route::get('/groups/{id_group}/addRound', ['as' => 'groups.add_round', 'uses' => 'GroupController@addRound']);
            Route::post('/groups/updateRounds', ['as' => 'groups.update_rounds', 'uses' => 'GroupController@updateRounds']);
            Route::post('/groups/teams/add', ['as' => 'groups.teams.add', 'uses' => 'GroupController@addTeam']);            
            Route::post('/groups/teams/remove', ['as' => 'groups.teams.remove', 'uses' => 'GroupController@removeTeam']);            
            Route::post('/groups/{id_group}/macro_calendar/save', ['as' => 'macro_calendar.save', 'uses' => 'RoundController@saveMacroCalendar']);
                
            Route::get('/rounds/{id_round}/macro_matches/add', ['as' => 'add_round_match', 'uses' => 'RoundController@addMacroMatch']);        
            Route::get('/rounds/{id_round}/delete', ['as' => 'delete_round_match', 'uses' => 'RoundController@delete']);  
            Route::get('/round/{id_round}/matches', ['as' => 'round_matches', 'uses' => 'RoundController@matches']);
            
            Route::post('/macro_match/{id_macro_match}/delete', ['as' => 'del_macro_match' , 'uses' => 'MacroMatchController@deleteMacroMatch']);
            Route::post('/macro_match/{id_macro_match}/makeNull', ['as' => 'match_null' , 'uses' => 'MacroMatchController@makeNull']);
            
            Route::post('/macro_match/{id_macro_match}/sub_match/add', ['as' => 'add_sub_match' , 'uses' => 'MacroMatchController@addSubMatch']);        
            
            Route::get('/matches/{id_match}/delete', ['as' => 'del_match' , 'uses' => 'MatchController@delete']);        
            Route::post('/matches/{id_match}/deleteAjax', ['as' => 'del_match' , 'uses' => 'MatchController@deleteAjax']);        

            Route::post('/brackets/teams/add', ['as' => 'brackets.teams.add', 'uses' => 'BracketController@addTeam']);            
            Route::post('/brackets/teams/remove', ['as' => 'brackets.teams.remove', 'uses' => 'BracketController@removeTeam']);            
            Route::post('/brackets/{id_bracket}/edit', ['as' => 'brackets.edit', 'uses' => 'BracketController@edit']);
            Route::post('/brackets/online', ['as' => 'brackets.online', 'uses' => 'BracketController@online']);        
            
            Route::get('/score/{id_match}', ['as' => 'score_match', 'uses' => 'ScoreController@getScore']);

            //Route::resource('groups', 'GroupController');        
            Route::resource('categories', 'CategoryController');     
                        
            /** Vittoria a tavolino */
            Route::post('/score/{id_match}/forfait', ['as' => 'match.forfait', 'uses' => 'ScoreController@forfait']);                       
            
            /* Vittori a tavolino squadra macro */
            Route::post('/score/{id_macro_match}/forfait_macro', ['as' => 'match.forfait_macro', 'uses' => 'ScoreController@forfaitMacro']);                       
            Route::post('/score/{id_macro_match}/remove_forfait_macro', ['as' => 'match.remove_forfait_macro', 'uses' => 'ScoreController@delForfaitMacro']);                       
            Route::post('/score/macro/{id_macro_match}/store', ['as' => 'macro_match.all_scores', 'uses' => 'ScoreController@storeAll']);                       
            
            Route::resource('userMetas', 'UserMetaController');        
            
            Route::resource('editionClubs', 'EditionClubController');
            Route::resource('editionTeams', 'EditionTeamController');            
            
            
            Route::resource('categoryTeams', 'CategoryTeamController');
            
            Route::resource('rounds', 'RoundController');
            Route::resource('matches', 'MatchController');
            
            Route::resource('classifications', 'ClassificationController');
            Route::resource('news', 'NewsController');
            Route::resource('newsCategories', 'NewsCategoryController');
            Route::resource('pages', 'PageController');
            Route::resource('infos', 'InfoController');
                       
            Route::resource('rankings', 'RankingController');
            
            /* Partners */
            Route::get('/partners', ['as'=>'partners.index', 'uses'=>'PartnerController@index']);
            Route::get('/partners/create', ['as'=>'partners.create', 'uses'=>'PartnerController@create']);
            Route::get('/partners/{id_partner}/edit', ['as'=>'partners.edit', 'uses'=>'PartnerController@edit']);
            Route::post('/partners/store', ['as'=>'partners.store', 'uses'=>'PartnerController@store']);            
            Route::post('/partners/update', ['as'=>'partners.update', 'uses'=>'PartnerController@update']);            
            Route::post('/partners/actions', ['as'=>'partners.actions', 'uses'=>'PartnerController@actions']);
            
            /** Gestione banner */
            Route::get('/banners', ['as'=>'banners.index', 'uses'=>'BannerController@banners']);
            Route::get('/banners/create', ['as'=>'banners.create', 'uses'=>'BannerController@create']);
            Route::post('/banners/store', ['as'=>'banners.store', 'uses'=>'BannerController@store']);
            Route::get('/banners/{id_banner}/edit', ['as'=>'banners.edit', 'uses'=>'BannerController@edit']);
            Route::post('/banners/update', ['as'=>'banners.update', 'uses'=>'BannerController@update']);

app/Models/Division.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Division
 * @package App\Models
 * @version April 28, 2019, 9:43 am UTC
 *
 * @property \App\Models\Category idCategory
 * @property \App\Models\CategoryType idCategoryType
 * @property \App\Models\Tournament idTournament
 * @property \App\Models\Zone idZone
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property \Illuminate\Database\Eloquent\Collection 
 * @property integer id_tournament
 * @property integer id_zone
 * @property integer id_category
 * @property integer id_category_type
 */
class Division extends Model
{
    //use SoftDeletes;

    public $table = 'divisions';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'id_tournament',
        'id_zone',
        'id_category',
        'id_category_type'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'id_tournament' => 'integer',
        'id_zone' => 'integer',
        'id_category' => 'integer',
        'id_category_type' => 'integer',
        'generated' => 'integer',
        'edit_mode' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'id_tournament' => 'required',
        'id_zone' => 'required',
        'id_category' => 'required',
        'id_category_type' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function category()
    {
        return $this->belongsTo(\App\Models\Category::class, 'id_category');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function categoryType()
    {
        return $this->belongsTo(\App\Models\CategoryType::class, 'id_category_type');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function tournament()
    {
        return $this->belongsTo(\App\Models\Tournament::class, 'id_tournament');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function zone()
    {
        return $this->belongsTo(\App\Models\Zone::class, 'id_zone');
    }

    public function groups(){
        return $this->hasMany(\App\Models\Group::class, 'id_division', 'id', 'groups');
    }
}

app/Http/Controllers/DivisionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

use Carbon\Carbon;

use App\Models\Division;
use App\Models\Tournament;
use App\Models\Zone;
use App\Models\Group;

class DivisionController extends Controller
{
     

    public function show($id_division){
        $groups = Group::where('id_division', '=', $id_division)
                        ->where('flag_online', '=', 1)
                        ->get();        
        return view('single-categoria')->with('groups', $groups);
    }
}

resources/views/admin/divisions/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Division
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'divisions.store']) !!}

                        @include('divisions.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/divisions/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Division
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($division, ['route' => ['divisions.update', $division->id], 'method' => 'patch']) !!}

                        @include('divisions.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/divisions/fields.blade.php
<!-- Id Tournament Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_tournament', 'Id Tournament:') !!}
    {!! Form::number('id_tournament', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Zone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_zone', 'Id Zone:') !!}
    {!! Form::number('id_zone', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Category Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_category', 'Id Category:') !!}
    {!! Form::number('id_category', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Category Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_category_type', 'Id Category Type:') !!}
    {!! Form::number('id_category_type', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('divisions.index') !!}" class="btn btn-default">{!! trans('labels.cancel'); !!}</a>
</div>

resources/views/admin/divisions/index.blade.php
@extends('admin.layouts.app')

@section('css')
<style>
    .twitter-typeahead{ width: 100% }
    .tt-menu{ width: 100% }
    .tt-dataset{ margin-top: -20px; }
</style>
@endsection

@section('content')   

<section class="content-header">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="{{ route('admin.editions.index') }}"><i class="fa fa-dashboard"></i> Edizione</a></li>
            <li><a href="{{ route('admin.subscriptions', ['id_tournament' => $division->tournament->id]) }}">Iscrizioni</a></li>                
        </ol>            
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h1 class="pull-left">            
                Gironi                 
                {!! $division->category->name !!}
                {!! $division->categoryType->name !!}        
                {!! $division->zone->city->name !!}
                {!! $division->zone->name !!}     
            </h1> 
        </div>
    </div>        
</section>



<div class="content">            

    <form action="{{ config('app.url') }}/admin/division/{!! $division->id !!}/edit">                    

        @include('adminlte-templates::common.errors')

        <div class="row">            
            <div class="col-sm-12 text-right">
                @csrf
                <input type="hidden" name="id_division" value="{!! $division->id !!}">

                @if($division->edit_mode)                                
                <button type="submit" name="btn_add_group" class="btn btn-warning"><i class="fa fa-plus"></i> Aggiungi girone</button>
                <button type="submit" name="btn_edit_groups" class="btn btn-primary"><i class="fa fa-check"></i> Esci da modifica</button>
                <button type="submit" name="btn_save_groups" class="btn btn-success"><i class="fa fa-check"></i> Salva gironi</button>
                @elseif( !$division->edit_mode )
                <button type="submit" name="btn_edit_groups" class="btn btn-warning"><i class="fa fa-edit"></i> Modifica gironi</button>
                @endif

            </div>
        </div>

        <div class="clearfix"></div>

        @include('flash::message')        

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">

                @if( in_array( $division->tournament->edition->edition_type , [0, 1] ) )
                @include('admin.divisions.table')                    
                @elseif( $division->tournament->edition->edition_type == 2 )
                @include('admin.divisions.table_macro')                    
                @endif

                @if($division->edit_mode)                                
                @include('admin.divisions.teams_not_in_groups')
                @endif
            </div>
        </div>
        <div class="text-center">

        </div>
    </form>       
</div>


<div id="modal-add-group-team" class="modal fade" tabindex="-1" role="dialog">            
    <div class="modal-dialog" role="document">            
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Torneo</h4>
            </div>
            <div class="modal-body">                    
                <div class="row">
                    <div class="col-xs-12">    

                        <form class="typeahead" role="search">
                            <div class="form-group">
                                <input type="search" name="q" id="search-input" class="form-control search-input" placeholder="Aggiungi giocatore" autocomplete="off">
                            </div>
                        </form>                            

                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        <!-- Name Field -->
                        <table class="table table-striped">
                            <thead>                                
                            <td>Giocatore</td>
                            <td>Email</td>                                
                            <td></td>
                            </thead>
                            <tbody id="tbody-team-players">

                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
            <div class="modal-footer">                        
                <input type="hidden" id="sel_player" value="">
                <input type="hidden" name="id_group" id="id_group" value="">
                <button type="button" class="btn btn-primary" onClick="addTeam()">{!! trans('labels.save') !!}</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">{!! trans('labels.cancel') !!}</button>
            </div>
        </div><!-- /.modal-content -->        
    </div><!-- /.modal-dialog -->                
</div><!-- /.modal -->

@endsection


@section('scripts')
<script>

    var add_players = [];
    var add_team_group = null;

    $(document).ready(function () {
        $("[id^=online-]").on('ifChanged', function () {
            var flag_online = $(this).is(':checked');

            var data = {
                "_token": "{{ csrf_token() }}",
                id_group: $(this).attr('id').split('-')[1],
                flag_online: flag_online
            }

            $.ajax({
                url: '{{ env('APP_URL') }}/admin/groups/online',
                type: 'post',
                data: data,
                success: function (res) {
                }
            });
        });

        // Set the Options for "Bloodhound" suggestion engine
        var engine = new Bloodhound({
            remote: {
                url: '{{ env('APP_URL') }}/admin/player/search?q=%QUERY%',
                wildcard: '%QUERY%'
            },
            datumTokenizer: Bloodhound.tokenizers.whitespace('q'),
            queryTokenizer: Bloodhound.tokenizers.whitespace
        });

        $(".search-input").change(function () {
            $("#player_id").val('');
        });

        $(".search-input").typeahead({
            hint: true,
            highlight: true,
            minLength: 3,
            afterSelect: function (item) {
                console.log("afterSelect", item, this.$element);
                this.$element[0].value = item.value
            }
        }, {
            source: engine.ttAdapter(),

            // This will be appended to "tt-dataset-" to form the class name of the suggestion menu.
            name: 'usersList',

            display: function (data) {
                return data.name + ' ' + data.surname
            },

            // the key from the array we want to display (name,id,email,etc...)
            templates: {

                empty: [
                    '<div class="list-group search-results-dropdown"><div class="list-group-item">Nothing found.</div></div>'
                ],
                header: [
                    '<div class="list-group search-results-dropdown">'
                ],
                suggestion: function (data) {
                    return '<a href="#" onClick="selectPlayer(' + data.id + ')" class="list-group-item">' + data.name + ' ' + data.surname + ' <br> ' + data.email + '</a>'
                }
            }
        });
    });

    function addGroupTeam(id_group) {
        add_team_group = id_group;
        add_players = [];
        $("#modal-add-group-team").modal('show');
    }

    function delGroup(id_group) {
        if (confirm("Eliminare il gruppo selezionato? Attenzione, eliminando il gruppo non sarà più possibile recuperare i dati!")) {
            $.ajax({
                url: '{{ env('APP_URL') }}/admin/groups/remove',
                data: {
                    "_token": "{{ csrf_token() }}",
                    id_group: id_group
                },
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    console.log(data);
                    document.location.reload();
                }
            });
        }
    }


    function makeCalendar(id_group) {
        if (confirm("Rigenerare il calendario per questo Girone?")) {
            $.ajax({
                url: '{{ env('APP_URL') }}/admin/groups/' + id_group + '/calendar/make',
                data: {
                    "_token": "{{ csrf_token() }}",
                    id_group: id_group
                },
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    console.log(data);
                    if (data.status == 'ok') {
                        alert("IL CALENDARIO E' STATO GENERATO!");
                    }
                }
            });
        }
    }



    function addTeam() {

        console.log($("#tbody-team-players").find('tr'));

        if ($("#tbody-team-players").find('tr').length < 2) {
            alert("La squadra deve contenere almeno 2 giocatori");
            return;
        }

        if ($("#tbody-team-players").find('tr').length > 3) {
            alert("La squadra deve contenere una sola riserva");
            return;
        }

        $.ajax({
            url: '{{ env('APP_URL') }}/admin/groups/teams/add',
            data: {
                "_token": "{{ csrf_token() }}",
                id_group: add_team_group,
                players: add_players
            },
            type: 'post',
            dataType: 'json',
            success: function (data) {

                console.log(data);

                add_team_group = null;
                add_players = [];

                if (data.status == 'ok') {
                    $("#modal-add-group-team").modal('hide');
                    document.location.reload();
                }
            }
        });
    }


    function removeTeamFromGroup(id_group, id_team) {

        if (confirm("Eliminare la squadra?")) {
            $.ajax({
                url: '{{ env('APP_URL') }}/admin/groups/teams/remove',
                data: {
                    "_token": "{{ csrf_token() }}",
                    id_group: id_group,
                    id_team: id_team
                },
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    if (data.status == 'ok') {
                        document.location.reload();
                    }
                }
            });
        }
    }

    function addTeamPlayer() {

        var id_player = $("#sel_player").val();
        $.ajax({
            url: '{{ env('APP_URL') }}/admin/player/' + id_player + '/get',
            type: 'get',
            dataType: 'json',
            success: function (data) {
                $("#sel_player").val('');
                $("#search-input").val('');

                console.log(data);

                var avatar = '';

                for (var i = 0; i < data.metas.length; i++) {
                    if (data.metas[i]) {
                        if (data.metas[i].meta == 'avatar') {
                            avatar = data.metas[i].meta_value;
                        }
                    }
                }

                var tipo = 'riserva';
                if ($("#tbody-team-players tr").length < 2) {
                    tipo = 'titolare';
                }

                add_players.push(id_player);

                var row = '<tr id="tr_player_' + data.id + '">';
                //row += '<td><img src="{!! env('APP_URL') !!}/storage/'+avatar+'" style="width: 30px; height: 30px" class="img-circle"></td>';
                row += '<td>' + data.name + ' ' + data.surname + '<input type="hidden" name="id_player" value="' + data.id + '"></td>';
                row += '<td>' + data.email + '</td>';
                row += '<td id="tipo_giocatore">' + tipo + '</td>';
                row += '<td><button type="button" class="btn btn-danger" onclick="removePlayer(' + data.id + ')"><i class="fa fa-trash-o"></i></button></td>';
                row += '</tr>';

                $("#tbody-team-players").append(row);
            }
        });
    }

    function selectPlayer(id_player) {
        $("#sel_player").val(id_player);
        addTeamPlayer();
    }

    function removePlayer(id_player) {
        $("#tr_player_" + id_player).remove();
        $("#search-input").val('');
        $("#tbody-team-players tr").each(function (k, val) {
            if (k <= 1) {
                $(this).find('#tipo_giocatore').html('titolare');
            } else {
                $(this).find('#tipo_giocatore').html('riserva');
            }
        });
    }
</script>
@endsection

resources/views/admin/divisions/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Division
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('divisions.show_fields')
                    <a href="{!! route('divisions.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/divisions/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $division->id !!}</p>
</div>

<!-- Id Tournament Field -->
<div class="form-group">
    {!! Form::label('id_tournament', 'Id Tournament:') !!}
    <p>{!! $division->id_tournament !!}</p>
</div>

<!-- Id Zone Field -->
<div class="form-group">
    {!! Form::label('id_zone', 'Id Zone:') !!}
    <p>{!! $division->id_zone !!}</p>
</div>

<!-- Id Category Field -->
<div class="form-group">
    {!! Form::label('id_category', 'Id Category:') !!}
    <p>{!! $division->id_category !!}</p>
</div>

<!-- Id Category Type Field -->
<div class="form-group">
    {!! Form::label('id_category_type', 'Id Category Type:') !!}
    <p>{!! $division->id_category_type !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $division->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $division->updated_at !!}</p>
</div>